version: '3'
services:
  web:
    build: .
    ports:
     - "8000:8000"
    environment:
     - SQLALCHEMY_DATABASE_URI=postgresql://bouker_events:passwd123@db/bouker_events
    volumes:
     - .:/bouker/
    links:
     - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=bouker_events
      - POSTGRES_USER=bouker_events
      - POSTGRES_PASSWORD=passwd123
    ports:
      - "5432:5432"
