"""empty message

Revision ID: 327544ce0f57
Revises:
Create Date: 2017-12-09 20:00:54.282869

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '327544ce0f57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=256), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('start_time', sa.DateTime(), nullable=False),
                    sa.Column('end_time', sa.DateTime(), nullable=True),
                    sa.Column('total', sa.Integer(), nullable=True),
                    sa.Column('taken', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
